# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc7ddc4f0f30637a4dbfe5562f7b43d0b4381b8e7c58009b3f3eb75bcdef702df861e5b0fd0399f7978f633b74f09a30c988c3e0cc0f2e65ce7b426d1451467

test:
  secret_key_base: 25edc3580f2e31fccc78362c152dcd70b71f63db35a5fe6a0db1b8f15fcd10c8af61cd239268de5d2abeb327303999ea059e1beafe0d6b597af340dba4bbfc16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
